export enum ErrorCode {
  // Config missing
  TEXT_TRANSLATE_CONFIG_MISSING = 'TEXT_TRANSLATE_CONFIG_MISSING',
  SCREENSHOT_DIRECT_CONFIG_MISSING = 'SCREENSHOT_DIRECT_CONFIG_MISSING',
  SCREENSHOT_EXTRACT_CONFIG_MISSING = 'SCREENSHOT_EXTRACT_CONFIG_MISSING',
  SCREENSHOT_TRANSLATE_CONFIG_MISSING = 'SCREENSHOT_TRANSLATE_CONFIG_MISSING',

  // Permission denied
  TEXT_TRANSLATE_PERMISSION_DENIED = 'TEXT_TRANSLATE_PERMISSION_DENIED',
  SCREENSHOT_DIRECT_PERMISSION_DENIED = 'SCREENSHOT_DIRECT_PERMISSION_DENIED',
  SCREENSHOT_EXTRACT_PERMISSION_DENIED = 'SCREENSHOT_EXTRACT_PERMISSION_DENIED',
  SCREENSHOT_TRANSLATE_PERMISSION_DENIED = 'SCREENSHOT_TRANSLATE_PERMISSION_DENIED',

  // API key / model missing
  TEXT_API_KEY_MISSING = 'TEXT_API_KEY_MISSING',
  SCREENSHOT_DIRECT_API_KEY_MISSING = 'SCREENSHOT_DIRECT_API_KEY_MISSING',
  SCREENSHOT_EXTRACT_API_KEY_MISSING = 'SCREENSHOT_EXTRACT_API_KEY_MISSING',
  SCREENSHOT_TRANSLATE_API_KEY_MISSING = 'SCREENSHOT_TRANSLATE_API_KEY_MISSING',
  TEXT_MODEL_MISSING = 'TEXT_MODEL_MISSING',
  VISION_MODEL_MISSING = 'VISION_MODEL_MISSING',

  // Input validation
  INVALID_INPUT = 'INVALID_INPUT',
  TEXT_TOO_LONG = 'TEXT_TOO_LONG',
  IMAGE_TOO_LARGE = 'IMAGE_TOO_LARGE',
  SCREENSHOT_REGION_INVALID = 'SCREENSHOT_REGION_INVALID',

  // Runtime errors
  SCREENSHOT_CAPTURE_FAILED = 'SCREENSHOT_CAPTURE_FAILED',
  VISION_MODEL_UNSUPPORTED = 'VISION_MODEL_UNSUPPORTED',
  UPSTREAM_TIMEOUT = 'UPSTREAM_TIMEOUT',
  UPSTREAM_BAD_RESPONSE = 'UPSTREAM_BAD_RESPONSE',
  NETWORK_ERROR = 'NETWORK_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
